#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtsensors
Version  : 5.15.2
Release  : 29
URL      : https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtsensors-everywhere-src-5.15.2.tar.xz
Source0  : https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtsensors-everywhere-src-5.15.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qtsensors-lib = %{version}-%{release}
Requires: qtsensors-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : pkgconfig(Qt5Bluetooth)
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5DBus)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(Qt5Xml)
Patch1: qtsensors-stable-branch.patch

%description
No detailed description available

%package dev
Summary: dev components for the qtsensors package.
Group: Development
Requires: qtsensors-lib = %{version}-%{release}
Provides: qtsensors-devel = %{version}-%{release}
Requires: qtsensors = %{version}-%{release}

%description dev
dev components for the qtsensors package.


%package examples
Summary: examples components for the qtsensors package.
Group: Default
Requires: qtsensors-dev = %{version}-%{release}

%description examples
examples components for the qtsensors package.


%package lib
Summary: lib components for the qtsensors package.
Group: Libraries
Requires: qtsensors-license = %{version}-%{release}

%description lib
lib components for the qtsensors package.


%package license
Summary: license components for the qtsensors package.
Group: Default

%description license
license components for the qtsensors package.


%prep
%setup -q -n qtsensors-everywhere-src-5.15.2
cd %{_builddir}/qtsensors-everywhere-src-5.15.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
%qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1652678335
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtsensors
cp %{_builddir}/qtsensors-everywhere-src-5.15.2/LICENSE.FDL %{buildroot}/usr/share/package-licenses/qtsensors/61907422fefcd2313a9b570c31d203a6dbebd333
cp %{_builddir}/qtsensors-everywhere-src-5.15.2/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/qtsensors/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/qtsensors-everywhere-src-5.15.2/LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/qtsensors/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/qtsensors-everywhere-src-5.15.2/LICENSE.GPL3-EXCEPT %{buildroot}/usr/share/package-licenses/qtsensors/e93757aefa405f2c9a8a55e780ae9c39542dfc3a
cp %{_builddir}/qtsensors-everywhere-src-5.15.2/LICENSE.LGPL3 %{buildroot}/usr/share/package-licenses/qtsensors/f45ee1c765646813b442ca58de72e20a64a7ddba
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/cmake/Qt5Sensors/Qt5Sensors_QCounterGesturePlugin.cmake

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qaccelerometer_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qaltimeter_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qambientlightsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qambienttemperaturesensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qcompass_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qdistancesensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qgyroscope_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qholstersensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qhumiditysensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qirproximitysensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qlidsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qlightsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qmagnetometer_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qorientationsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qpressuresensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qproximitysensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qrotationsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qsensorbackend_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qsensorgesture_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qsensorgesturemanagerprivate_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qtapsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qtiltsensor_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/qtsensors-config_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/sensorlog_p.h
/usr/include/qt5/QtSensors/5.15.2/QtSensors/private/simulatorgesturescommon_p.h
/usr/include/qt5/QtSensors/QAccelerometer
/usr/include/qt5/QtSensors/QAccelerometerFilter
/usr/include/qt5/QtSensors/QAccelerometerReading
/usr/include/qt5/QtSensors/QAltimeter
/usr/include/qt5/QtSensors/QAltimeterFilter
/usr/include/qt5/QtSensors/QAltimeterReading
/usr/include/qt5/QtSensors/QAmbientLightFilter
/usr/include/qt5/QtSensors/QAmbientLightReading
/usr/include/qt5/QtSensors/QAmbientLightSensor
/usr/include/qt5/QtSensors/QAmbientTemperatureFilter
/usr/include/qt5/QtSensors/QAmbientTemperatureReading
/usr/include/qt5/QtSensors/QAmbientTemperatureSensor
/usr/include/qt5/QtSensors/QCompass
/usr/include/qt5/QtSensors/QCompassFilter
/usr/include/qt5/QtSensors/QCompassReading
/usr/include/qt5/QtSensors/QDistanceFilter
/usr/include/qt5/QtSensors/QDistanceReading
/usr/include/qt5/QtSensors/QDistanceSensor
/usr/include/qt5/QtSensors/QGyroscope
/usr/include/qt5/QtSensors/QGyroscopeFilter
/usr/include/qt5/QtSensors/QGyroscopeReading
/usr/include/qt5/QtSensors/QHolsterFilter
/usr/include/qt5/QtSensors/QHolsterReading
/usr/include/qt5/QtSensors/QHolsterSensor
/usr/include/qt5/QtSensors/QHumidityFilter
/usr/include/qt5/QtSensors/QHumidityReading
/usr/include/qt5/QtSensors/QHumiditySensor
/usr/include/qt5/QtSensors/QIRProximityFilter
/usr/include/qt5/QtSensors/QIRProximityReading
/usr/include/qt5/QtSensors/QIRProximitySensor
/usr/include/qt5/QtSensors/QLidFilter
/usr/include/qt5/QtSensors/QLidReading
/usr/include/qt5/QtSensors/QLidSensor
/usr/include/qt5/QtSensors/QLightFilter
/usr/include/qt5/QtSensors/QLightReading
/usr/include/qt5/QtSensors/QLightSensor
/usr/include/qt5/QtSensors/QMagnetometer
/usr/include/qt5/QtSensors/QMagnetometerFilter
/usr/include/qt5/QtSensors/QMagnetometerReading
/usr/include/qt5/QtSensors/QOrientationFilter
/usr/include/qt5/QtSensors/QOrientationReading
/usr/include/qt5/QtSensors/QOrientationSensor
/usr/include/qt5/QtSensors/QPressureFilter
/usr/include/qt5/QtSensors/QPressureReading
/usr/include/qt5/QtSensors/QPressureSensor
/usr/include/qt5/QtSensors/QProximityFilter
/usr/include/qt5/QtSensors/QProximityReading
/usr/include/qt5/QtSensors/QProximitySensor
/usr/include/qt5/QtSensors/QRotationFilter
/usr/include/qt5/QtSensors/QRotationReading
/usr/include/qt5/QtSensors/QRotationSensor
/usr/include/qt5/QtSensors/QSensor
/usr/include/qt5/QtSensors/QSensorBackend
/usr/include/qt5/QtSensors/QSensorBackendFactory
/usr/include/qt5/QtSensors/QSensorChangesInterface
/usr/include/qt5/QtSensors/QSensorFilter
/usr/include/qt5/QtSensors/QSensorGesture
/usr/include/qt5/QtSensors/QSensorGestureManager
/usr/include/qt5/QtSensors/QSensorGesturePluginInterface
/usr/include/qt5/QtSensors/QSensorGestureRecognizer
/usr/include/qt5/QtSensors/QSensorManager
/usr/include/qt5/QtSensors/QSensorPluginInterface
/usr/include/qt5/QtSensors/QSensorReading
/usr/include/qt5/QtSensors/QTapFilter
/usr/include/qt5/QtSensors/QTapReading
/usr/include/qt5/QtSensors/QTapSensor
/usr/include/qt5/QtSensors/QTiltFilter
/usr/include/qt5/QtSensors/QTiltReading
/usr/include/qt5/QtSensors/QTiltSensor
/usr/include/qt5/QtSensors/QtSensors
/usr/include/qt5/QtSensors/QtSensorsDepends
/usr/include/qt5/QtSensors/QtSensorsVersion
/usr/include/qt5/QtSensors/qaccelerometer.h
/usr/include/qt5/QtSensors/qaltimeter.h
/usr/include/qt5/QtSensors/qambientlightsensor.h
/usr/include/qt5/QtSensors/qambienttemperaturesensor.h
/usr/include/qt5/QtSensors/qcompass.h
/usr/include/qt5/QtSensors/qdistancesensor.h
/usr/include/qt5/QtSensors/qgyroscope.h
/usr/include/qt5/QtSensors/qholstersensor.h
/usr/include/qt5/QtSensors/qhumiditysensor.h
/usr/include/qt5/QtSensors/qirproximitysensor.h
/usr/include/qt5/QtSensors/qlidsensor.h
/usr/include/qt5/QtSensors/qlightsensor.h
/usr/include/qt5/QtSensors/qmagnetometer.h
/usr/include/qt5/QtSensors/qorientationsensor.h
/usr/include/qt5/QtSensors/qpressuresensor.h
/usr/include/qt5/QtSensors/qproximitysensor.h
/usr/include/qt5/QtSensors/qrotationsensor.h
/usr/include/qt5/QtSensors/qsensor.h
/usr/include/qt5/QtSensors/qsensorbackend.h
/usr/include/qt5/QtSensors/qsensorgesture.h
/usr/include/qt5/QtSensors/qsensorgesturemanager.h
/usr/include/qt5/QtSensors/qsensorgestureplugininterface.h
/usr/include/qt5/QtSensors/qsensorgesturerecognizer.h
/usr/include/qt5/QtSensors/qsensormanager.h
/usr/include/qt5/QtSensors/qsensorplugin.h
/usr/include/qt5/QtSensors/qsensorsglobal.h
/usr/include/qt5/QtSensors/qtapsensor.h
/usr/include/qt5/QtSensors/qtiltsensor.h
/usr/include/qt5/QtSensors/qtsensors-config.h
/usr/include/qt5/QtSensors/qtsensorsversion.h
/usr/lib64/cmake/Qt5Sensors/Qt5SensorsConfig.cmake
/usr/lib64/cmake/Qt5Sensors/Qt5SensorsConfigVersion.cmake
/usr/lib64/cmake/Qt5Sensors/Qt5Sensors_IIOSensorProxySensorPlugin.cmake
/usr/lib64/cmake/Qt5Sensors/Qt5Sensors_LinuxSensorPlugin.cmake
/usr/lib64/cmake/Qt5Sensors/Qt5Sensors_QShakeSensorGesturePlugin.cmake
/usr/lib64/cmake/Qt5Sensors/Qt5Sensors_QtSensorGesturePlugin.cmake
/usr/lib64/cmake/Qt5Sensors/Qt5Sensors_genericSensorPlugin.cmake
/usr/lib64/libQt5Sensors.prl
/usr/lib64/libQt5Sensors.so
/usr/lib64/pkgconfig/Qt5Sensors.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri

%files examples
%defattr(-,root,root,-)
/usr/share/qt5/examples/sensors/accelbubble/Info.plist
/usr/share/qt5/examples/sensors/accelbubble/accelbubble.pro
/usr/share/qt5/examples/sensors/accelbubble/accelbubble.qml
/usr/share/qt5/examples/sensors/accelbubble/accelbubble.qrc
/usr/share/qt5/examples/sensors/accelbubble/android/AndroidManifest.xml
/usr/share/qt5/examples/sensors/accelbubble/content/Bluebubble.svg
/usr/share/qt5/examples/sensors/accelbubble/main.cpp
/usr/share/qt5/examples/sensors/grue/Grue/qmldir
/usr/share/qt5/examples/sensors/grue/console_app/console_app.pro
/usr/share/qt5/examples/sensors/grue/console_app/main.cpp
/usr/share/qt5/examples/sensors/grue/grue.png
/usr/share/qt5/examples/sensors/grue/grue.pro
/usr/share/qt5/examples/sensors/grue/grue.qml
/usr/share/qt5/examples/sensors/grue/grue.xcf
/usr/share/qt5/examples/sensors/grue/icon.xcf
/usr/share/qt5/examples/sensors/grue/import/import.json
/usr/share/qt5/examples/sensors/grue/import/import.pro
/usr/share/qt5/examples/sensors/grue/import/main.cpp
/usr/share/qt5/examples/sensors/grue/import/qmldir
/usr/share/qt5/examples/sensors/grue/lib/gruesensor.cpp
/usr/share/qt5/examples/sensors/grue/lib/gruesensor.h
/usr/share/qt5/examples/sensors/grue/lib/gruesensor_p.h
/usr/share/qt5/examples/sensors/grue/lib/lib.pri
/usr/share/qt5/examples/sensors/grue/lib/lib.pro
/usr/share/qt5/examples/sensors/grue/main.cpp
/usr/share/qt5/examples/sensors/grue/plugin/gruesensorimpl.cpp
/usr/share/qt5/examples/sensors/grue/plugin/gruesensorimpl.h
/usr/share/qt5/examples/sensors/grue/plugin/main.cpp
/usr/share/qt5/examples/sensors/grue/plugin/plugin.json
/usr/share/qt5/examples/sensors/grue/plugin/plugin.pro
/usr/share/qt5/examples/sensors/grue/qml.pro
/usr/share/qt5/examples/sensors/grue/qml.qrc
/usr/share/qt5/examples/sensors/maze/Congratulation.qml
/usr/share/qt5/examples/sensors/maze/LabyrinthSquare.qml
/usr/share/qt5/examples/sensors/maze/Mouse.qml
/usr/share/qt5/examples/sensors/maze/android/AndroidManifest.xml
/usr/share/qt5/examples/sensors/maze/components/ApplicationWindow.qml
/usr/share/qt5/examples/sensors/maze/components/Button.qml
/usr/share/qt5/examples/sensors/maze/components/images/button_background_disabled.png
/usr/share/qt5/examples/sensors/maze/components/images/button_background_normal.png
/usr/share/qt5/examples/sensors/maze/components/images/button_background_pressed.png
/usr/share/qt5/examples/sensors/maze/content/00.png
/usr/share/qt5/examples/sensors/maze/content/01.png
/usr/share/qt5/examples/sensors/maze/content/cheese.png
/usr/share/qt5/examples/sensors/maze/content/cheeseeating.gif
/usr/share/qt5/examples/sensors/maze/content/congratulations.gif
/usr/share/qt5/examples/sensors/maze/content/mouse_down.gif
/usr/share/qt5/examples/sensors/maze/content/start.png
/usr/share/qt5/examples/sensors/maze/lib.js
/usr/share/qt5/examples/sensors/maze/main.cpp
/usr/share/qt5/examples/sensors/maze/maze.pro
/usr/share/qt5/examples/sensors/maze/maze.qml
/usr/share/qt5/examples/sensors/maze/maze.qrc
/usr/share/qt5/examples/sensors/qmlqtsensors/components/ApplicationWindow.qml
/usr/share/qt5/examples/sensors/qmlqtsensors/components/Button.qml
/usr/share/qt5/examples/sensors/qmlqtsensors/components/Divider.qml
/usr/share/qt5/examples/sensors/qmlqtsensors/components/images/button_background_disabled.png
/usr/share/qt5/examples/sensors/qmlqtsensors/components/images/button_background_normal.png
/usr/share/qt5/examples/sensors/qmlqtsensors/components/images/button_background_pressed.png
/usr/share/qt5/examples/sensors/qmlqtsensors/main.cpp
/usr/share/qt5/examples/sensors/qmlqtsensors/qmlqtsensors.pro
/usr/share/qt5/examples/sensors/qmlqtsensors/qmlqtsensors.qml
/usr/share/qt5/examples/sensors/qmlqtsensors/qmlqtsensors.qrc
/usr/share/qt5/examples/sensors/qmlsensorgestures/Button.qml
/usr/share/qt5/examples/sensors/qmlsensorgestures/GestureList.qml
/usr/share/qt5/examples/sensors/qmlsensorgestures/GestureView.qml
/usr/share/qt5/examples/sensors/qmlsensorgestures/GesturesView.qml
/usr/share/qt5/examples/sensors/qmlsensorgestures/main.cpp
/usr/share/qt5/examples/sensors/qmlsensorgestures/plugin/plugin.pro
/usr/share/qt5/examples/sensors/qmlsensorgestures/plugin/qcountergestureplugin.cpp
/usr/share/qt5/examples/sensors/qmlsensorgestures/plugin/qcountergestureplugin.h
/usr/share/qt5/examples/sensors/qmlsensorgestures/plugin/qcounterrecognizer.cpp
/usr/share/qt5/examples/sensors/qmlsensorgestures/plugin/qcounterrecognizer.h
/usr/share/qt5/examples/sensors/qmlsensorgestures/qml.pro
/usr/share/qt5/examples/sensors/qmlsensorgestures/qml.qrc
/usr/share/qt5/examples/sensors/qmlsensorgestures/qmlsensorgestures.pro
/usr/share/qt5/examples/sensors/qmlsensorgestures/qmlsensorgestures.qml
/usr/share/qt5/examples/sensors/sensor_explorer/Explorer/qmldir
/usr/share/qt5/examples/sensors/sensor_explorer/import/explorer.cpp
/usr/share/qt5/examples/sensors/sensor_explorer/import/explorer.h
/usr/share/qt5/examples/sensors/sensor_explorer/import/import.json
/usr/share/qt5/examples/sensors/sensor_explorer/import/import.pro
/usr/share/qt5/examples/sensors/sensor_explorer/import/main.cpp
/usr/share/qt5/examples/sensors/sensor_explorer/import/main.h
/usr/share/qt5/examples/sensors/sensor_explorer/import/propertyinfo.cpp
/usr/share/qt5/examples/sensors/sensor_explorer/import/propertyinfo.h
/usr/share/qt5/examples/sensors/sensor_explorer/import/qmldir
/usr/share/qt5/examples/sensors/sensor_explorer/import/sensoritem.cpp
/usr/share/qt5/examples/sensors/sensor_explorer/import/sensoritem.h
/usr/share/qt5/examples/sensors/sensor_explorer/main.cpp
/usr/share/qt5/examples/sensors/sensor_explorer/qml.pro
/usr/share/qt5/examples/sensors/sensor_explorer/qml.qrc
/usr/share/qt5/examples/sensors/sensor_explorer/sensor_explorer.pro
/usr/share/qt5/examples/sensors/sensor_explorer/sensor_explorer.qml
/usr/share/qt5/examples/sensors/sensorgestures/main.cpp
/usr/share/qt5/examples/sensors/sensorgestures/mainwindow.cpp
/usr/share/qt5/examples/sensors/sensorgestures/mainwindow.h
/usr/share/qt5/examples/sensors/sensorgestures/mainwindow.ui
/usr/share/qt5/examples/sensors/sensorgestures/sensorgestures.pro
/usr/share/qt5/examples/sensors/sensors.pro
/usr/share/qt5/examples/sensors/shakeit/audio/loopy2a_mono.wav
/usr/share/qt5/examples/sensors/shakeit/audio/phone.wav
/usr/share/qt5/examples/sensors/shakeit/content/triangle.png
/usr/share/qt5/examples/sensors/shakeit/content/triangle2.png
/usr/share/qt5/examples/sensors/shakeit/content/triangle3.png
/usr/share/qt5/examples/sensors/shakeit/main.cpp
/usr/share/qt5/examples/sensors/shakeit/shakeit.pro
/usr/share/qt5/examples/sensors/shakeit/shakeit.qml
/usr/share/qt5/examples/sensors/shakeit/shakeit.qrc
/usr/share/qt5/examples/sensors/stub.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5Sensors.so.5
/usr/lib64/libQt5Sensors.so.5.15
/usr/lib64/libQt5Sensors.so.5.15.2
/usr/lib64/qt5/plugins/sensorgestures/libqtsensorgestures_plugin.so
/usr/lib64/qt5/plugins/sensorgestures/libqtsensorgestures_shakeplugin.so
/usr/lib64/qt5/plugins/sensors/libqtsensors_generic.so
/usr/lib64/qt5/plugins/sensors/libqtsensors_iio-sensor-proxy.so
/usr/lib64/qt5/plugins/sensors/libqtsensors_linuxsys.so
/usr/lib64/qt5/qml/QtSensors/libdeclarative_sensors.so
/usr/lib64/qt5/qml/QtSensors/plugins.qmltypes
/usr/lib64/qt5/qml/QtSensors/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtsensors/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qtsensors/61907422fefcd2313a9b570c31d203a6dbebd333
/usr/share/package-licenses/qtsensors/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qtsensors/e93757aefa405f2c9a8a55e780ae9c39542dfc3a
/usr/share/package-licenses/qtsensors/f45ee1c765646813b442ca58de72e20a64a7ddba
